# Generated by Django 5.1.15 on 2026-04-28 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('objetos_en_cesta', models.IntegerField()),
                ('total', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_expiracion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20, unique=True)),
                ('pais_origen', models.CharField(blank=True, max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('anio_fundacion', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('PROC', 'Procesando'), ('ENV', 'Enviado'), ('ENT', 'Entregado')], default='PEND', max_length=4)),
                ('direccion_envio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('correo', models.EmailField(db_column='email_usuario', max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(max_length=50)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tienda.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('talla', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3)),
                ('descuento', models.ManyToManyField(to='Tienda.descuento')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.marca')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='prenda',
            field=models.ManyToManyField(through='Tienda.DetallePedido', to='Tienda.prenda'),
        ),
        migrations.CreateModel(
            name='ItemCesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('fecha_agregado', models.DateTimeField(auto_now_add=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.cesta')),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.prenda')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_disponible', models.PositiveIntegerField(default=0)),
                ('ubicacion_almacen', models.CharField(blank=True, max_length=255)),
                ('stock_minimo', models.PositiveIntegerField(default=1)),
                ('stock_maximo', models.PositiveIntegerField(default=100)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.prenda')),
            ],
        ),
        migrations.AddField(
            model_name='detallepedido',
            name='prenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.prenda'),
        ),
        migrations.AddField(
            model_name='cesta',
            name='prenda',
            field=models.ManyToManyField(through='Tienda.ItemCesta', to='Tienda.prenda'),
        ),
        migrations.CreateModel(
            name='Perfil_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apodo', models.CharField(max_length=20, unique=True)),
                ('biografia', models.TextField(max_length=200)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tienda.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.usuario'),
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion', models.PositiveIntegerField(default=5)),
                ('comentario', models.TextField(blank=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('recomendado', models.BooleanField(default=True)),
                ('prenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.prenda')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tienda.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cesta',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Tienda.usuario'),
        ),
    ]
