# Generated by Django 5.1.15 on 2026-04-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_alter_cesta_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemcesta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
