# Generated by Django 5.1.15 on 2026-04-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0004_alter_detallepedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
